Shopping/Controllers/CartItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Shopping.Models;

namespace Shopping.Controllers
{
    public class CartItemsController : Controller
    {
        private readonly shopContext _context;

        public CartItemsController(shopContext context)
        {
            _context = context;
        }
       

        // GET: CartItems
        public async Task<IActionResult> Index()
        {
            var shopContext = _context.CartItems.Include(c => c.products);
            return View(await shopContext.ToListAsync());
        }

        // GET: CartItems/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cartItem = await _context.CartItems
                .Include(c => c.products)
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (cartItem == null)
            {
                return NotFound();
            }

            return View(cartItem);
        }

        // GET: CartItems/Create
        public IActionResult Create()
        {
            ViewData["Product_id"] = new SelectList(_context.Products, "Product_id", "Product_id");
            return View();
        }

        // POST: CartItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ItemId,CartId,Quantity,DateCreated,Product_id")] CartItem cartItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cartItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Product_id"] = new SelectList(_context.Products, "Product_id", "Product_id", cartItem.Product_id);
            return View(cartItem);
        }

        // GET: CartItems/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cartItem = await _context.CartItems.FindAsync(id);
            if (cartItem == null)
            {
                return NotFound();
            }
            ViewData["Product_id"] = new SelectList(_context.Products, "Product_id", "Product_id", cartItem.Product_id);
            return View(cartItem);
        }

        // POST: CartItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ItemId,CartId,Quantity,DateCreated,Product_id")] CartItem cartItem)
        {
            if (id != cartItem.ItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cartItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartItemExists(cartItem.ItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Product_id"] = new SelectList(_context.Products, "Product_id", "Product_id", cartItem.Product_id);
            return View(cartItem);
        }

        // GET: CartItems/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cartItem = await _context.CartItems
                .Include(c => c.products)
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (cartItem == null)
            {
                return NotFound();
            }

            return View(cartItem);
        }

        // POST: CartItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var cartItem = await _context.CartItems.FindAsync(id);
            _context.CartItems.Remove(cartItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult AddToCart()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddToCart(string id) {
            
            CartItem cart = new CartItem();
            cart.ItemId = id;
            cart.DateCreated=DateTime.Now;
            
            cart.CartId = HttpContext.Session.GetString("Username");
            cart.Quantity = 1;
            cart.Product_id = id;
            _context.CartItems.Add(cart);
            _context.SaveChanges();
            
            return View(cart);
        }

        private bool CartItemExists(string id)
        {
            return _context.CartItems.Any(e => e.ItemId == id);
        }
    }
}

Shopping/Controllers/LoginController.cs
using Shopping.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Microsoft.AspNetCore.Routing;

namespace Shopping.Controllers
{
    public class LoginController : Controller 
    {
        private readonly shopContext db;
        private readonly ISession session;
        public LoginController(shopContext _db, IHttpContextAccessor httpContextAccessor)
        {
            db = _db;
            session = httpContextAccessor.HttpContext.Session;
        }
        public IActionResult Index()
        {
            ViewBag.Username=HttpContext.Session.GetString("Username");
            return View(db.Sellers.ToList());
        }
      
       
        public IActionResult login()
        {

            return View();
        }
        [HttpPost]
        public IActionResult login(Seller obj)
        {
            var result = (from i in db.Sellers where i.Seller_id == obj.Seller_id
                                                     && i.Password == obj.Password select i).SingleOrDefault();
            if (result != null)
            {
                HttpContext.Session.SetString("Username", result.Seller_name);
                return RedirectToAction("Index", "Sellers");

            }
            else
                return View();
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index","Home");
        }
        public IActionResult Register()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Register(Seller u)
        {
            db.Sellers.Add(u);
            db.SaveChanges();
            return RedirectToAction("login");
        }
        public IActionResult CustomerRegister()
        {

            return View();
        }
        [HttpPost]
        public IActionResult CustomerRegister(Customer u)
        {
            ViewBag.age = u.age;
            HttpContext.Session.SetInt32("age",u.age);
            db.Customers.Add(u);
            db.SaveChanges();
            return RedirectToAction("Customerlogin");
        }
        public IActionResult Customerlogin()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Customerlogin(Customer obj)
        {
            var result = (from i in db.Customers where i.Customer_id == obj.Customer_id && i.Password == obj.Password select i).SingleOrDefault();
            if (result != null)
            {
                HttpContext.Session.SetString("Username", result.Customer_name);
                

            }
            var routeValues = new RouteValueDictionary {
            { "id", result.Customer_id }
           
            };
            return RedirectToAction("Details", "Customers",routeValues);
        }


    }
}

Shopping/Controllers/ProductController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Shopping.Models;
using Shopping.ViewModel;
using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using Shopping.DAL;
using System.Collections.Generic;

namespace Shopping.Controllers
{
    public class ProductController : Controller
    {
        private readonly shopContext _shopContext;
        public IProductRepo _productRepo { get; set; }
        private ISellerRepo _sellerRepo { get; set; }
        private IProductMapRepo _productMapRepo { get; set; } 
        private IWebHostEnvironment _env;
        public ProductController(shopContext db, IWebHostEnvironment env)
        {
            _shopContext = db;
            _productRepo = new ProductRepo(new shopContext());
            _sellerRepo = new SellerRepo(new shopContext());
            _productMapRepo = new ProductMapRepo(new shopContext());
            _env = env;
        }
        
       
       
        
        
       
        public IActionResult ProductHome()
        {
            return View();
        }

        #region product crud operations
        public async Task<IActionResult> Index()
        {
         //Here, I use normal method to list the products instead of Repo.
            return View(await _shopContext.Products.ToListAsync());
            //return View(await _productRepo.GetProductList());
        }
        // GET: Product/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var products = await _productRepo.GetProductById(id);
            if (products == null)
            {
                return NotFound();
            }

            return View(products);
        }

        public async Task<IActionResult> createProduct()
        {
            //drop down for seller id in product table. 

            var result = new SelectList(from i in await _sellerRepo.GetSellerList() select i.Seller_id).ToList();
            ViewBag.Seller_id = result;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> createProduct(Product p)
        {
            
            if (p.Pimage != null)
            {
                var uploads = Path.Combine(_env.WebRootPath, "Uploads");
                var filePath = Path.Combine(uploads, p.Pimage.FileName);

                p.Pimage.CopyTo(new FileStream(filePath, FileMode.Create));
                p.ImageName = p.Pimage.FileName; 
            }


            await _productRepo.InsertProduct(p);
            await _productRepo.Save();
         
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _productRepo.GetProductById(id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Sellers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {

            await _productRepo.DeleteProduct(id);
            await _productRepo.Save();
            return RedirectToAction(nameof(Index));
        }
#endregion

        public IActionResult AllProductLocation()
        {
            return View(_productMapRepo.GetProductMapList());
        }
        public async Task<IActionResult> AddProductLocation()
        {
            var result = new SelectList(from i in await _productRepo.GetProductList() select i.Product_id).ToList();
            ViewBag.Product_Id = result;
            return View();
        }
        [HttpPost]
        public IActionResult AddProductLocation(ProductMap pm)
        {
            _productMapRepo.InsertProductMap(pm);
            _productMapRepo.Save();
            return RedirectToAction("AllProductLocation");
        }
        public IActionResult ProductLocationDetails(string id)
        {
            
            if (id == null)
            {
                return NotFound();
            }

            var product = _productMapRepo.GetProductMapList()
                .FirstOrDefault(m => m.TrackId == id);
            if (product == null)
            {
                return NotFound();
            }

            string location = product.PLocation;
             
            string[] locat = location.Split(", ");
            ViewBag.Location = locat;

            return View(product);
        }
        public IActionResult SearchProduct()
        {
            return View();
        }
       
        [HttpPost]
        public async Task<IActionResult> SearchResult(string SearchPhrase)
        {
            var a = await _productRepo.GetProductList();
            
            return View(a.Where(i => i.Product_name.Contains(SearchPhrase)).ToList());
        }
        
        // Note....
        public IActionResult Direction(string id)
        {

            StringBuilder t = new StringBuilder();
            foreach (var i in _productMapRepo.GetProductMapList())
            {

                if (id != i.Product_id)
                {

                    continue;
                }
                else
                {
                    t.Append(i.TrackId);
                    break;
                }
            }

            ProductMap productMap = _productMapRepo.GetProductMapById(t.ToString());
            string s = productMap.PLocation;
            List<string> list = new List<string>();
            list = s.Split(',').ToList();
            ViewData["List"] = list;
            
            
            return View(productMap);
            
        }
        #region Seller
        public async Task<IActionResult> SellerByProductId(string id)
        {

            StringBuilder t = new StringBuilder();
            foreach (var i in await _productRepo.GetProductList())
            {

                if (id != i.Product_id)
                {

                    continue;
                }
                else
                {
                    t.Append(i.Seller_id);
                    break;
                }
            }

            Seller sellers =await _sellerRepo.GetSellerById(t.ToString()); 
            return View(sellers);
        }
        #endregion:ByProduct
        public async Task<IActionResult> SortByCategory()
        {
            var result = new SelectList(from i in await _productRepo.GetProductList() select i.type).ToList();
            ViewBag.type = result;
            return View();
        }
        
        public async Task<IActionResult> SortByCategory(string id)
        {
            var a=await _productRepo.GetProductList();
            return View("Index",a.Where(i => i.type.Contains(id)).ToList());
        }
        public async Task<IActionResult> SellerOtherProducts(string id)
        {
            var a = await _productRepo.GetProductList();
            return View("Index",a.Where(i => i.Seller_id==id).ToList());   
        }

    }
}

Shopping/Controllers/PurchaseController.cs
using Microsoft.AspNetCore.Mvc;
using Shopping.Models;

namespace Shopping.Controllers
{
    public class PurchaseController : Controller
    {
        private readonly shopContext _shopContext;
        public PurchaseController(shopContext db)
        {
            _shopContext = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult OffersForSenior(int id)
        {
           //Customer cust = _shopContext.Customers.Find(id);
            int age = id;
            if (age <= 40)
            {
                ViewBag.Offer = "Hey, Sorry. You didn't get the Offer";
            }
            else if(age>40 && age <= 50)
            {
                ViewBag.Offer = 10;
            }
            else if(age>50 && age<60)
            {
                ViewBag.Offer = 20;
            }
            else
            {
                ViewBag.Offer = 30;
            }

            return View();

        }
      
    }
}

Shopping/Views/Shared/MyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shopping</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/mystylesheet2.css" />
    <script src="https://kit.fontawesome.com/7d64766b1e.js" crossorigin="anonymous"></script>

</head>
<body>
    <header>
       
           <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
          <div class="container-fluid">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">Ivan Yaaro</a>
             <a class="navbar-brand text-success logo h1 align-self-center" href="~/css/horizontal_on_white_by_logaster.png">
             <img src="~/css/horizontal_on_white_by_logaster.png" height="50" width="100"/>
            </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active"  asp-controller="Home" asp-action="Index">Home
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-controller="Sellers" asp-action="Index" onclick="mainController.pleaseWait()">Sellers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"  asp-controller="Customers" asp-action="Index" onclick="mainController.pleaseWait()">Customers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"  asp-controller="Product" asp-action="Index" onclick="mainController.pleaseWait()">Products</a>
        </li>
       
     
      </ul>
     
      <form class="d-flex">
      
        <button class="btn btn-secondary my-2 my-sm-0" type="submit" asp-controller="Product" asp-action="SearchProduct" onclick="mainController.pleaseWait();">Search</button>
      </form>
    </div>
     <partial name="_LoginPartial" />
  </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" >
        <div class="container" style="background-color:lightgreen;">
            &copy; 2022 - Shopping - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>

                    <a class="text-light" href="https://fb.com/" target="_blank" rel="sponsored"><i class="fa-brands fa-facebook"></i></a>                    <a class="text-light" href="https://www.instagram.com/" target="_blank"><i class="bi bi-instagram bi-sm "></i></a>
                    <a class="text-light" href="https://twitter.com/" target="_blank"><i class="fa-brands fa-twitter-square"></i></a>
                    <a class="text-light" href="https://www.linkedin.com/" target="_blank"><i class="fa-brands fa-linkedin"></i></a> 
                    <a class="text-light" href="https://www.instagram.com/" target="_blank"><i class="fa-brands fa-instagram-square"></i></a>  
                    
        </div>
    </footer>
    <div class="container">
    <div id="pleaseWait"
         class="pleaseWaitMessage d-none">
        <h4>
            <span id="theWaitMessage">
             Please wait while loading...
            </span>
        </h4>
    </div>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Shopping/Views/Shared/SellerLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shopping</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/mystylesheet2.css" />
    <script src="https://kit.fontawesome.com/7d64766b1e.js" crossorigin="anonymous"></script>

</head>
<body>
    <header>
        
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" asp-controller="Home" asp-action="Index">Ivan Yaaro</a>
     <a class="navbar-brand text-success logo h1 align-self-center" href="~/css/horizontal_on_white_by_logaster.png">
                <img src="~/css/horizontal_on_white_by_logaster.png" height="50" width="100"/>
            </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active"  asp-controller="Home" asp-action="Index">Home
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-controller="Sellers" asp-action="Index">Sellers</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"  asp-controller="Product" asp-action="createProduct">Add Product</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"  asp-controller="Product" asp-action="AddProductLocation">Map_Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link"  asp-controller="Product" asp-action="AllProductLocation">Products_Location</a>
        </li> 
        <button class="btn btn-secondary my-2 my-sm-0" type="submit" asp-controller="Product" asp-action="SearchProduct">Search</button>
      </ul>
    </div>
     <partial name="_LoginPartial" />
  </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" >
        <div class="container" style="background-color:lightgreen;">
            &copy; 2022 - Shopping - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
           
                    <a class="text-light" href="https://fb.com/" target="_blank" rel="sponsored"><i class="fa-brands fa-facebook"></i></a>                    <a class="text-light" href="https://www.instagram.com/" target="_blank"><i class="bi bi-instagram bi-sm "></i></a>
                    <a class="text-light" href="https://twitter.com/" target="_blank"><i class="fa-brands fa-twitter-square"></i></a>
                    <a class="text-light" href="https://www.linkedin.com/" target="_blank"><i class="fa-brands fa-linkedin"></i></a> 
                    <a class="text-light" href="https://www.instagram.com/" target="_blank"><i class="fa-brands fa-instagram-square"></i></a>  
                    
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Shopping/Views/Shared/_CustomerPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Customer

@{
    var showButtons = (bool)ViewData["ShowButtons"];
}
<div class="card m-3" style="min-width:18rem; max-width:30.5%;">
          
            <div class="card-header">
                <h3 style="color:red; animation-name:revert">@Model.Customer_name</h3>
            </div>
            
            <div>
               <bold>I am <p style="color:orangered;">@Model.age</p></bold>
            </div>
            <div>
                @{
            if(Model.gender == "Male" || Model.gender == "male" || Model.gender=="M")
            {
                                <img class="card-img-top imageThumbnail" src="~/img/images Male.png" alt="Male"/>
            }
            else
            {
                                <img class="card-img-top imageThumbnail" src="~/img/female-profile-picture-drawing_csp14385991.webp" alt="Female"/>
            }

                   }
            </div>
            <div>
                <a class="navbar-sm-brand text-light text-decoration-none" href="tel:@Model.phoneNumber">Call Me</a>
            </div>
    @if (showButtons)
    {
        <div class="card-footer text-brown-center m-4">
            <a class="btn btn-primary" asp-action="OffersForSenior" asp-controller="Purchase" asp-route-id="@Model.age">Offer</a> |
            <a class="btn btn-primary" asp-action="Edit" asp-controller="Customers" asp-route-id="@Model.Customer_id">Edit</a> |
            <a class="btn btn-primary" asp-action="Details" asp-route-id="@Model.Customer_id">Details</a> |
            <a class="btn btn-secondary" asp-action="Delete" asp-route-id="@Model.Customer_id">Delete</a>
        </div>
    }
</div>

Shopping/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shopping</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Shopping</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="login">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Shopping - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Shopping/Views/Shared/_ProductPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Product
@{
   var showDelete = (bool)ViewData["ShowDelete"];
}
 
        <div class="card m-3" style="min-width:18rem; max-width:30.5%; " >
                <div class="card-header">
                    <h3 style="color:darkorange"  class="card-title" >@Model.Product_name</h3>
                    </div>
                    <h4 class="card-subtitle mb-2 text-muted">@Model.type</h4>
                    <p class="card-text"> @Model.Product_description</p>
                    <h3 style="color:orange">@Model.Price</h3>
                   
                    @{
                        var photopath = @Model.ImageName ?? "Planet9_3840x2160.jpg";
                    }
                    <div class="card-img">
                        <img src="~/Uploads/@photopath" alt="Product image" height="100" width="100"/>
                    </div>
     
           
                @*<button><a asp-controller="CartItems" asp-action="AddToCart" asp-route-id="@item.Product_id">Add To Cart</a></button> *@
        <div class="container">
            <div class="row">
            <div class="col"> <a class="btn btn-primary" asp-action="Details" asp-controller="Product" asp-route-id="@Model.Product_id">Details</a> </div>
                <div class="col"><a class="btn btn-primary" asp-action="Direction" asp-controller="Product" asp-route-id="@Model.Product_id">Direction</a></div>
                <div class="col"><a class="btn btn-primary" asp-controller="Product" asp-action="SellerByProductId"  asp-route-id="@Model.Product_id">Seller</a> </div>
                @if(showDelete)
                {
                    <div class="col"><a class="btn btn-outline-danger m-lg-1" asp-action="Delete" asp-route-id="@Model.Product_id">Delete</a></div>
                }
            </div>
        </div>
        </div>